# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Parse-Java
version:      0.01_01
version_from: lib/Parse/Java.pm
installdirs:  site
requires:
    Class::Accessor:               0
    Parse::Yapp:                   0
    Test::More:                    0
    version:                       0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
